<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Country;

class CountrySeeder extends Seeder
{
    public function run()

    {
        Country::truncate();
        $countries = [
            ['name' => 'Afghanistan', 'code' => 'AF', 'nationality' => 'Afghan', 'continent' => 'Asia'],
            ['name' => 'Åland Islands', 'code' => 'AX', 'nationality' => 'Ålandic', 'continent' => 'Europe'],
            ['name' => 'Albania', 'code' => 'AL', 'nationality' => 'Albanian', 'continent' => 'Europe'],
            ['name' => 'Algeria', 'code' => 'DZ', 'nationality' => 'Algerian', 'continent' => 'Africa'],
            ['name' => 'American Samoa', 'code' => 'AS', 'nationality' => 'American Samoan', 'continent' => 'Oceania'],
            ['name' => 'Andorra', 'code' => 'AD', 'nationality' => 'Andorran', 'continent' => 'Europe'],
            ['name' => 'Angola', 'code' => 'AO', 'nationality' => 'Angolan', 'continent' => 'Africa'],
            ['name' => 'Anguilla', 'code' => 'AI', 'nationality' => 'Anguillian', 'continent' => 'North America'],
            ['name' => 'Antarctica', 'code' => 'AQ', 'nationality' => 'Antarctican', 'continent' => 'Antarctica'],
            ['name' => 'Antigua and Barbuda', 'code' => 'AG', 'nationality' => 'Antiguan', 'continent' => 'North America'],
            ['name' => 'Argentina', 'code' => 'AR', 'nationality' => 'Argentine', 'continent' => 'South America'],
            ['name' => 'Armenia', 'code' => 'AM', 'nationality' => 'Armenian', 'continent' => 'Asia'],
            ['name' => 'Aruba', 'code' => 'AW', 'nationality' => 'Aruban', 'continent' => 'North America'],
            ['name' => 'Australia', 'code' => 'AU', 'nationality' => 'Australian', 'continent' => 'Oceania'],
            ['name' => 'Austria', 'code' => 'AT', 'nationality' => 'Austrian', 'continent' => 'Europe'],
            ['name' => 'Azerbaijan', 'code' => 'AZ', 'nationality' => 'Azerbaijani', 'continent' => 'Asia'],
            ['name' => 'Bahamas', 'code' => 'BS', 'nationality' => 'Bahamian', 'continent' => 'North America'],
            ['name' => 'Bahrain', 'code' => 'BH', 'nationality' => 'Bahraini', 'continent' => 'Asia'],
            ['name' => 'Bangladesh', 'code' => 'BD', 'nationality' => 'Bangladeshi', 'continent' => 'Asia'],
            ['name' => 'Barbados', 'code' => 'BB', 'nationality' => 'Barbadian', 'continent' => 'North America'],
            ['name' => 'Belarus', 'code' => 'BY', 'nationality' => 'Belarusian', 'continent' => 'Europe'],
            ['name' => 'Belgium', 'code' => 'BE', 'nationality' => 'Belgian', 'continent' => 'Europe'],
            ['name' => 'Belize', 'code' => 'BZ', 'nationality' => 'Belizean', 'continent' => 'North America'],
            ['name' => 'Benin', 'code' => 'BJ', 'nationality' => 'Beninese', 'continent' => 'Africa'],
            ['name' => 'Bermuda', 'code' => 'BM', 'nationality' => 'Bermudian', 'continent' => 'North America'],
            ['name' => 'Bhutan', 'code' => 'BT', 'nationality' => 'Bhutanese', 'continent' => 'Asia'],
            ['name' => 'Bolivia, Plurinational State of', 'code' => 'BO', 'nationality' => 'Bolivian', 'continent' => 'South America'],
            ['name' => 'Bonaire, Sint Eustatius and Saba', 'code' => 'BQ', 'nationality' => 'Bonairean', 'continent' => 'North America'],
            ['name' => 'Bosnia and Herzegovina', 'code' => 'BA', 'nationality' => 'Bosnian', 'continent' => 'Europe'],
            ['name' => 'Botswana', 'code' => 'BW', 'nationality' => 'Botswana', 'continent' => 'Africa'],
            ['name' => 'Bouvet Island', 'code' => 'BV', 'nationality' => 'Bouvet Islander', 'continent' => 'Antarctica'],
            ['name' => 'Brazil', 'code' => 'BR', 'nationality' => 'Brazilian', 'continent' => 'South America'],
            ['name' => 'British Indian Ocean Territory', 'code' => 'IO', 'continent' => 'Asia'],
            ['name' => 'Brunei Darussalam', 'code' => 'BN', 'nationality' => 'Bruneian', 'continent' => 'Asia'],
            ['name' => 'Bulgaria', 'code' => 'BG', 'nationality' => 'Bulgarian', 'continent' => 'Europe'],
            ['name' => 'Burkina Faso', 'code' => 'BF', 'nationality' => 'Burkinabè', 'continent' => 'Africa'],
            ['name' => 'Burundi', 'code' => 'BI', 'nationality' => 'Burundian', 'continent' => 'Africa'],
            ['name' => 'Cambodia', 'code' => 'KH', 'nationality' => 'Cambodian', 'continent' => 'Asia'],
            ['name' => 'Cameroon', 'code' => 'CM', 'nationality' => 'Cameroonian', 'continent' => 'Africa'],
            ['name' => 'Canada', 'code' => 'CA', 'nationality' => 'Canadian', 'continent' => 'North America'],
            ['name' => 'Cape Verde', 'code' => 'CV', 'nationality' => 'Cabo Verdean', 'continent' => 'Africa'],
            ['name' => 'Cayman Islands', 'code' => 'KY', 'nationality' => 'Caymanian', 'continent' => 'North America'],
            ['name' => 'Central African Republic', 'code' => 'CF', 'nationality' => 'Central African', 'continent' => 'Africa'],
            ['name' => 'Chad', 'code' => 'TD', 'nationality' => 'Chadian', 'continent' => 'Africa'],
            ['name' => 'Chile', 'code' => 'CL', 'nationality' => 'Chilean', 'continent' => 'South America'],
            ['name' => 'China', 'code' => 'CN', 'nationality' => 'Chinese', 'continent' => 'Asia'],
            ['name' => 'Christmas Island', 'code' => 'CX', 'nationality' => 'Christmas Islander', 'continent' => 'Oceania'],
            ['name' => 'Cocos (Keeling) Islands', 'code' => 'CC', 'nationality' => 'Cocos Islander', 'continent' => 'Oceania'],
            ['name' => 'Colombia', 'code' => 'CO', 'nationality' => 'Colombian', 'continent' => 'South America'],
            ['name' => 'Comoros', 'code' => 'KM', 'nationality' => 'Comorian', 'continent' => 'Africa'],
            ['name' => 'Congo', 'code' => 'CG', 'nationality' => 'Congolese', 'continent' => 'Africa'],
            ['name' => 'Congo, the Democratic Republic of the', 'code' => 'CD', 'nationality' => 'Congolese', 'continent' => 'Africa'],
            ['name' => 'Cook Islands', 'code' => 'CK', 'nationality' => 'Cook Islander', 'continent' => 'Oceania'],
            ['name' => 'Costa Rica', 'code' => 'CR', 'nationality' => 'Costa Rican', 'continent' => 'North America'],
            ['name' => 'Côte d\'Ivoire', 'code' => 'CI', 'nationality' => 'Ivorian', 'continent' => 'Africa'],
            ['name' => 'Croatia', 'code' => 'HR', 'nationality' => 'Croatian', 'continent' => 'Europe'],
            ['name' => 'Cuba', 'code' => 'CU', 'nationality' => 'Cuban', 'continent' => 'North America'],
            ['name' => 'Curaçao', 'code' => 'CW', 'nationality' => 'Curaçaoan', 'continent' => 'North America'],
            ['name' => 'Cyprus', 'code' => 'CY', 'nationality' => 'Cypriot', 'continent' => 'Europe'],
            ['name' => 'Czech Republic', 'code' => 'CZ', 'nationality' => 'Czech', 'continent' => 'Europe'],
            ['name' => 'Denmark', 'code' => 'DK', 'nationality' => 'Danish', 'continent' => 'Europe'],
            ['name' => 'Djibouti', 'code' => 'DJ', 'nationality' => 'Djiboutian', 'continent' => 'Africa'],
            ['name' => 'Dominica', 'code' => 'DM', 'nationality' => 'Dominican', 'continent' => 'North America'],
            ['name' => 'Dominican Republic', 'code' => 'DO', 'nationality' => 'Dominican', 'continent' => 'North America'],
            ['name' => 'Ecuador', 'code' => 'EC', 'nationality' => 'Ecuadorian', 'continent' => 'South America'],
            ['name' => 'Egypt', 'code' => 'EG', 'nationality' => 'Egyptian', 'continent' => 'Africa'],
            ['name' => 'El Salvador', 'code' => 'SV', 'nationality' => 'Salvadoran', 'continent' => 'North America'],
            ['name' => 'Equatorial Guinea', 'code' => 'GQ', 'nationality' => 'Equatoguinean', 'continent' => 'Africa'],
            ['name' => 'Eritrea', 'code' => 'ER', 'nationality' => 'Eritrean', 'continent' => 'Africa'],
            ['name' => 'Estonia', 'code' => 'EE', 'nationality' => 'Estonian', 'continent' => 'Europe'],
            ['name' => 'Ethiopia', 'code' => 'ET', 'nationality' => 'Ethiopian', 'continent' => 'Africa'],
            ['name' => 'Falkland Islands (Malvinas)', 'code' => 'FK', 'nationality' => 'Falkland Islander', 'continent' => 'South America'],
            ['name' => 'Faroe Islands', 'code' => 'FO', 'nationality' => 'Faroese', 'continent' => 'Europe'],
            ['name' => 'Fiji', 'code' => 'FJ', 'nationality' => 'Fijian', 'continent' => 'Oceania'],
            ['name' => 'Finland', 'code' => 'FI', 'nationality' => 'Finnish', 'continent' => 'Europe'],
            ['name' => 'France', 'code' => 'FR', 'nationality' => 'French', 'continent' => 'Europe'],
            ['name' => 'French Guiana', 'code' => 'GF', 'nationality' => 'French Guianese', 'continent' => 'South America'],
            ['name' => 'French Polynesia', 'code' => 'PF', 'nationality' => 'French Polynesian', 'continent' => 'Oceania'],
            ['name' => 'French Southern Territories', 'code' => 'TF', 'nationality' => 'French Southern Territories', 'continent' => 'Antarctica'],
            ['name' => 'Gabon', 'code' => 'GA', 'nationality' => 'Gabonese', 'continent' => 'Africa'],
            ['name' => 'Gambia', 'code' => 'GM', 'nationality' => 'Gambian', 'continent' => 'Africa'],
            ['name' => 'Georgia', 'code' => 'GE', 'nationality' => 'Georgian', 'continent' => 'Europe'],
            ['name' => 'Germany', 'code' => 'DE', 'nationality' => 'German', 'continent' => 'Europe'],
            ['name' => 'Ghana', 'code' => 'GH', 'nationality' => 'Ghanaian', 'continent' => 'Africa'],
            ['name' => 'Gibraltar', 'code' => 'GI', 'nationality' => 'Gibraltarian', 'continent' => 'Europe'],
            ['name' => 'Greece', 'code' => 'GR', 'nationality' => 'Greek', 'continent' => 'Europe'],
            ['name' => 'Greenland', 'code' => 'GL', 'nationality' => 'Greenlandic', 'continent' => 'North America'],
            ['name' => 'Grenada', 'code' => 'GD', 'nationality' => 'Grenadian', 'continent' => 'North America'],
            ['name' => 'Guadeloupe', 'code' => 'GP', 'nationality' => 'Guadeloupean', 'continent' => 'North America'],
            ['name' => 'Guam', 'code' => 'GU', 'nationality' => 'Guamanian', 'continent' => 'Oceania'],
            ['name' => 'Guatemala', 'code' => 'GT', 'nationality' => 'Guatemalan', 'continent' => 'North America'],
            ['name' => 'Guernsey', 'code' => 'GG', 'nationality' => 'Guernsey', 'continent' => 'Europe'],
            ['name' => 'Guinea', 'code' => 'GN', 'nationality' => 'Guinean', 'continent' => 'Africa'],
            ['name' => 'Guinea-Bissau', 'code' => 'GW', 'nationality' => 'Bissau-Guinean', 'continent' => 'Africa'],
            ['name' => 'Guyana', 'code' => 'GY', 'nationality' => 'Guyanese', 'continent' => 'South America'],
            ['name' => 'Haiti', 'code' => 'HT', 'nationality' => 'Haitian', 'continent' => 'North America'],
            ['name' => 'Heard Island and McDonald Mcdonald Islands', 'code' => 'HM', 'nationality' => 'Heard Island or McDonald Islander', 'continent' => 'Antarctica'],
            ['name' => 'Holy See (Vatican City State)', 'code' => 'VA', 'nationality' => 'Vatican', 'continent' => 'Europe'],
            ['name' => 'Honduras', 'code' => 'HN', 'nationality' => 'Honduran', 'continent' => 'North America'],
            ['name' => 'Hong Kong', 'code' => 'HK', 'nationality' => 'Hong Konger', 'continent' => 'Asia'],
            ['name' => 'Hungary', 'code' => 'HU', 'nationality' => 'Hungarian', 'continent' => 'Europe'],
            ['name' => 'Iceland', 'code' => 'IS', 'nationality' => 'Icelandic', 'continent' => 'Europe'],
            ['name' => 'India', 'code' => 'IN', 'nationality' => 'Indian', 'continent' => 'Asia'],
            ['name' => 'Indonesia', 'code' => 'ID', 'nationality' => 'Indonesian', 'continent' => 'Asia'],
            ['name' => 'Iran, Islamic Republic of', 'code' => 'IR', 'nationality' => 'Iranian', 'continent' => 'Asia'],
            ['name' => 'Iraq', 'code' => 'IQ', 'nationality' => 'Iraqi', 'continent' => 'Asia'],
            ['name' => 'Ireland', 'code' => 'IE', 'nationality' => 'Irish', 'continent' => 'Europe'],
            ['name' => 'Isle of Man', 'code' => 'IM', 'nationality' => 'Manx', 'continent' => 'Europe'],
            ['name' => 'Israel', 'code' => 'IL', 'nationality' => 'Israeli', 'continent' => 'Asia'],
            ['name' => 'Italy', 'code' => 'IT', 'nationality' => 'Italian', 'continent' => 'Europe'],
            ['name' => 'Jamaica', 'code' => 'JM', 'nationality' => 'Jamaican', 'continent' => 'North America'],
            ['name' => 'Japan', 'code' => 'JP', 'nationality' => 'Japanese', 'continent' => 'Asia'],
            ['name' => 'Jersey', 'code' => 'JE', 'nationality' => 'Jerseyman', 'continent' => 'Europe'],
            ['name' => 'Jordan', 'code' => 'JO', 'nationality' => 'Jordanian', 'continent' => 'Asia'],
            ['name' => 'Kazakhstan', 'code' => 'KZ', 'nationality' => 'Kazakhstani', 'continent' => 'Asia'],
            ['name' => 'Kenya', 'code' => 'KE', 'nationality' => 'Kenyan', 'continent' => 'Africa'],
            ['name' => 'Kiribati', 'code' => 'KI', 'nationality' => 'I-Kiribati', 'continent' => 'Oceania'],
            ['name' => 'Korea, Democratic People\'s Republic of', 'code' => 'KP', 'nationality' => 'North Korean', 'continent' => 'Asia'],
            ['name' => 'Korea, Republic of', 'code' => 'KR', 'nationality' => 'South Korean', 'continent' => 'Asia'],
            ['name' => 'Kuwait', 'code' => 'KW', 'nationality' => 'Kuwaiti', 'continent' => 'Asia'],
            ['name' => 'Kyrgyzstan', 'code' => 'KG', 'nationality' => 'Kyrgyzstani', 'continent' => 'Asia'],
            ['name' => 'Lao People\'s Democratic Republic', 'code' => 'LA', 'nationality' => 'Lao', 'continent' => 'Asia'],
            ['name' => 'Latvia', 'code' => 'LV', 'nationality' => 'Latvian', 'continent' => 'Europe'],
            ['name' => 'Lebanon', 'code' => 'LB', 'nationality' => 'Lebanese', 'continent' => 'Asia'],
            ['name' => 'Lesotho', 'code' => 'LS', 'nationality' => 'Basotho', 'continent' => 'Africa'],
            ['name' => 'Liberia', 'code' => 'LR', 'nationality' => 'Liberian', 'continent' => 'Africa'],
            ['name' => 'Libya', 'code' => 'LY', 'nationality' => 'Libyan', 'continent' => 'Africa'],
            ['name' => 'Liechtenstein', 'code' => 'LI', 'nationality' => 'Liechtensteiner', 'continent' => 'Europe'],
            ['name' => 'Lithuania', 'code' => 'LT', 'nationality' => 'Lithuanian', 'continent' => 'Europe'],
            ['name' => 'Luxembourg', 'code' => 'LU', 'nationality' => 'Luxembourgish', 'continent' => 'Europe'],
            ['name' => 'Macao', 'code' => 'MO', 'nationality' => 'Macanese', 'continent' => 'Asia'],
            ['name' => 'Macedonia, the Former Yugoslav Republic of', 'code' => 'MK', 'nationality' => 'Macedonian', 'continent' => 'Europe'],
            ['name' => 'Madagascar', 'code' => 'MG', 'nationality' => 'Malagasy', 'continent' => 'Africa'],
            ['name' => 'Malawi', 'code' => 'MW', 'nationality' => 'Malawian', 'continent' => 'Africa'],
            ['name' => 'Malaysia', 'code' => 'MY', 'nationality' => 'Malaysian', 'continent' => 'Asia'],
            ['name' => 'Maldives', 'code' => 'MV', 'nationality' => 'Maldivian', 'continent' => 'Asia'],
            ['name' => 'Mali', 'code' => 'ML', 'nationality' => 'Malian', 'continent' => 'Africa'],
            ['name' => 'Malta', 'code' => 'MT', 'nationality' => 'Maltese', 'continent' => 'Europe'],
            ['name' => 'Marshall Islands', 'code' => 'MH', 'nationality' => 'Marshallese', 'continent' => 'Oceania'],
            ['name' => 'Martinique', 'code' => 'MQ', 'nationality' => 'Martiniquais', 'continent' => 'North America'],
            ['name' => 'Mauritania', 'code' => 'MR', 'nationality' => 'Mauritanian', 'continent' => 'Africa'],
            ['name' => 'Mauritius', 'code' => 'MU', 'nationality' => 'Mauritian', 'continent' => 'Africa'],
            ['name' => 'Mayotte', 'code' => 'YT', 'nationality' => 'Mahorais', 'continent' => 'Africa'],
            ['name' => 'Mexico', 'code' => 'MX', 'nationality' => 'Mexican', 'continent' => 'North America'],
            ['name' => 'Micronesia, Federated States of', 'code' => 'FM', 'nationality' => 'Micronesian', 'continent' => 'Oceania'],
            ['name' => 'Moldova, Republic of', 'code' => 'MD', 'nationality' => 'Moldovan', 'continent' => 'Europe'],
            ['name' => 'Monaco', 'code' => 'MC', 'nationality' => 'Monegasque', 'continent' => 'Europe'],
            ['name' => 'Mongolia', 'code' => 'MN', 'nationality' => 'Mongolian', 'continent' => 'Asia'],
            ['name' => 'Montenegro', 'code' => 'ME', 'nationality' => 'Montenegrin', 'continent' => 'Europe'],
            ['name' => 'Montserrat', 'code' => 'MS', 'nationality' => 'Montserratian', 'continent' => 'North America'],
            ['name' => 'Morocco', 'code' => 'MA', 'nationality' => 'Moroccan', 'continent' => 'Africa'],
            ['name' => 'Mozambique', 'code' => 'MZ', 'nationality' => 'Mozambican', 'continent' => 'Africa'],
            ['name' => 'Myanmar', 'code' => 'MM', 'nationality' => 'Myanmarese', 'continent' => 'Asia'],
            ['name' => 'Namibia', 'code' => 'NA', 'nationality' => 'Namibian', 'continent' => 'Africa'],
            ['name' => 'Nauru', 'code' => 'NR', 'nationality' => 'Nauruan', 'continent' => 'Oceania'],
            ['name' => 'Nepal', 'code' => 'NP', 'nationality' => 'Nepali', 'continent' => 'Asia'],
            ['name' => 'Netherlands', 'code' => 'NL', 'nationality' => 'Dutch', 'continent' => 'Europe'],
            ['name' => 'New Caledonia', 'code' => 'NC', 'nationality' => 'New Caledonian', 'continent' => 'Oceania'],
            ['name' => 'New Zealand', 'code' => 'NZ', 'nationality' => 'New Zealander', 'continent' => 'Oceania'],
            ['name' => 'Nicaragua', 'code' => 'NI', 'nationality' => 'Nicaraguan', 'continent' => 'North America'],
            ['name' => 'Niger', 'code' => 'NE', 'nationality' => 'Nigerien', 'continent' => 'Africa'],
            ['name' => 'Nigeria', 'code' => 'NG', 'nationality' => 'Nigerian', 'continent' => 'Africa'],
            ['name' => 'Niue', 'code' => 'NU', 'nationality' => 'Niuean', 'continent' => 'Oceania'],
            ['name' => 'Norfolk Island', 'code' => 'NF', 'nationality' => 'Norfolk Islander', 'continent' => 'Oceania'],
            ['name' => 'Northern Mariana Islands', 'code' => 'MP', 'nationality' => 'Northern Mariana Islander', 'continent' => 'Oceania'],
            ['name' => 'Norway', 'code' => 'NO', 'nationality' => 'Norwegian', 'continent' => 'Europe'],
            ['name' => 'Oman', 'code' => 'OM', 'nationality' => 'Omani', 'continent' => 'Asia'],
            ['name' => 'Pakistan', 'code' => 'PK', 'nationality' => 'Pakistani', 'continent' => 'Asia'],
            ['name' => 'Palau', 'code' => 'PW', 'nationality' => 'Palauan', 'continent' => 'Oceania'],
            ['name' => 'Palestine, State of', 'code' => 'PS', 'nationality' => 'Palestinian', 'continent' => 'Asia'],
            ['name' => 'Panama', 'code' => 'PA', 'nationality' => 'Panamanian', 'continent' => 'North America'],
            ['name' => 'Papua New Guinea', 'code' => 'PG', 'nationality' => 'Papua New Guinean', 'continent' => 'Oceania'],
            ['name' => 'Paraguay', 'code' => 'PY', 'nationality' => 'Paraguayan', 'continent' => 'South America'],
            ['name' => 'Peru', 'code' => 'PE', 'nationality' => 'Peruvian', 'continent' => 'South America'],
            ['name' => 'Philippines', 'code' => 'PH', 'nationality' => 'Filipino', 'continent' => 'Asia'],
            ['name' => 'Pitcairn', 'code' => 'PN', 'nationality' => 'Pitcairn Islander', 'continent' => 'Oceania'],
            ['name' => 'Poland', 'code' => 'PL', 'nationality' => 'Polish', 'continent' => 'Europe'],
            ['name' => 'Portugal', 'code' => 'PT', 'nationality' => 'Portuguese', 'continent' => 'Europe'],
            ['name' => 'Puerto Rico', 'code' => 'PR', 'nationality' => 'Puerto Rican', 'continent' => 'North America'],
            ['name' => 'Qatar', 'code' => 'QA', 'nationality' => 'Qatari', 'continent' => 'Asia'],
            ['name' => 'Réunion', 'code' => 'RE', 'nationality' => 'Réunionese', 'continent' => 'Africa'],
            ['name' => 'Romania', 'code' => 'RO', 'nationality' => 'Romanian', 'continent' => 'Europe'],
            ['name' => 'Russian Federation', 'code' => 'RU', 'nationality' => 'Russian', 'continent' => 'Europe'],
            ['name' => 'Rwanda', 'code' => 'RW', 'nationality' => 'Rwandan', 'continent' => 'Africa'],
            ['name' => 'Saint Barthélemy', 'code' => 'BL', 'nationality' => 'Saint Barthélemy', 'continent' => 'North America'],
            ['name' => 'Saint Helena, Ascension and Tristan da Cunha', 'code' => 'SH', 'nationality' => 'Saint Helenian', 'continent' => 'Africa'],
            ['name' => 'Saint Kitts and Nevis', 'code' => 'KN', 'nationality' => 'Kittitian', 'continent' => 'North America'],
            ['name' => 'Saint Lucia', 'code' => 'LC', 'nationality' => 'Saint Lucian', 'continent' => 'North America'],
            ['name' => 'Saint Martin (French part)', 'code' => 'MF', 'nationality' => 'Saint Martinois', 'continent' => 'North America'],
            ['name' => 'Saint Pierre and Miquelon', 'code' => 'PM', 'nationality' => 'Saint-Pierrais', 'continent' => 'North America'],
            ['name' => 'Saint Vincent and the Grenadines', 'code' => 'VC', 'nationality' => 'Saint Vincentian', 'continent' => 'North America'],
            ['name' => 'Samoa', 'code' => 'WS', 'nationality' => 'Samoan', 'continent' => 'Oceania'],
            ['name' => 'San Marino', 'code' => 'SM', 'nationality' => 'Sammarinese', 'continent' => 'Europe'],
            ['name' => 'Sao Tome and Principe', 'code' => 'ST', 'nationality' => 'Sao Tomean', 'continent' => 'Africa'],
            ['name' => 'Saudi Arabia', 'code' => 'SA', 'nationality' => 'Saudi', 'continent' => 'Asia'],
            ['name' => 'Senegal', 'code' => 'SN', 'nationality' => 'Senegalese', 'continent' => 'Africa'],
            ['name' => 'Serbia', 'code' => 'RS', 'nationality' => 'Serbian', 'continent' => 'Europe'],
            ['name' => 'Seychelles', 'code' => 'SC', 'nationality' => 'Seychellois', 'continent' => 'Africa'],
            ['name' => 'Sierra Leone', 'code' => 'SL', 'nationality' => 'Sierra Leonean', 'continent' => 'Africa'],
            ['name' => 'Singapore', 'code' => 'SG', 'nationality' => 'Singaporean', 'continent' => 'Asia'],
            ['name' => 'Sint Maarten (Dutch part)', 'code' => 'SX', 'nationality' => 'Sint Maartener', 'continent' => 'North America'],
            ['name' => 'Slovakia', 'code' => 'SK', 'nationality' => 'Slovak', 'continent' => 'Europe'],
            ['name' => 'Slovenia', 'code' => 'SI', 'nationality' => 'Slovenian', 'continent' => 'Europe'],
            ['name' => 'Solomon Islands', 'code' => 'SB', 'nationality' => 'Solomon Islander', 'continent' => 'Oceania'],
            ['name' => 'Somalia', 'code' => 'SO', 'nationality' => 'Somali', 'continent' => 'Africa'],
            ['name' => 'South Africa', 'code' => 'ZA', 'nationality' => 'South African', 'continent' => 'Africa'],
            ['name' => 'South Georgia and the South Sandwich Islands', 'code' => 'GS', 'continent' => 'Antarctica'],
            ['name' => 'South Sudan', 'code' => 'SS', 'nationality' => 'South Sudanese', 'continent' => 'Africa'],
            ['name' => 'Spain', 'code' => 'ES', 'nationality' => 'Spanish', 'continent' => 'Europe'],
            ['name' => 'Sri Lanka', 'code' => 'LK', 'nationality' => 'Sri Lankan', 'continent' => 'Asia'],
            ['name' => 'Sudan', 'code' => 'SD', 'nationality' => 'Sudanese', 'continent' => 'Africa'],
            ['name' => 'Suriname', 'code' => 'SR', 'nationality' => 'Surinamese', 'continent' => 'South America'],
            ['name' => 'Svalbard and Jan Mayen', 'code' => 'SJ', 'nationality' => 'Svalbardian', 'continent' => 'Europe'],
            ['name' => 'Swaziland', 'code' => 'SZ', 'nationality' => 'Swazi', 'continent' => 'Africa'],
            ['name' => 'Sweden', 'code' => 'SE', 'nationality' => 'Swedish', 'continent' => 'Europe'],
            ['name' => 'Switzerland', 'code' => 'CH', 'nationality' => 'Swiss', 'continent' => 'Europe'],
            ['name' => 'Syrian Arab Republic', 'code' => 'SY', 'nationality' => 'Syrian', 'continent' => 'Asia'],
            ['name' => 'Taiwan', 'code' => 'TW', 'nationality' => 'Taiwanese', 'continent' => 'Asia'],
            ['name' => 'Tajikistan', 'code' => 'TJ', 'nationality' => 'Tajikistani', 'continent' => 'Asia'],
            ['name' => 'Tanzania, United Republic of', 'code' => 'TZ', 'nationality' => 'Tanzanian', 'continent' => 'Africa'],
            ['name' => 'Thailand', 'code' => 'TH', 'nationality' => 'Thai', 'continent' => 'Asia'],
            ['name' => 'Timor-Leste', 'code' => 'TL', 'nationality' => 'Timorese', 'continent' => 'Asia'],
            ['name' => 'Togo', 'code' => 'TG', 'nationality' => 'Togolese', 'continent' => 'Africa'],
            ['name' => 'Tokelau', 'code' => 'TK', 'nationality' => 'Tokelauan', 'continent' => 'Oceania'],
            ['name' => 'Tonga', 'code' => 'TO', 'nationality' => 'Tongan', 'continent' => 'Oceania'],
            ['name' => 'Trinidad and Tobago', 'code' => 'TT', 'nationality' => 'Trinidadian', 'continent' => 'North America'],
            ['name' => 'Tunisia', 'code' => 'TN', 'nationality' => 'Tunisian', 'continent' => 'Africa'],
            ['name' => 'Turkey', 'code' => 'TR', 'nationality' => 'Turkish', 'continent' => 'Europe'],
            ['name' => 'Turkmenistan', 'code' => 'TM', 'nationality' => 'Turkmen', 'continent' => 'Asia'],
            ['name' => 'Turks and Caicos Islands', 'code' => 'TC', 'nationality' => 'Turks and Caicos Islander', 'continent' => 'North America'],
            ['name' => 'Tuvalu', 'code' => 'TV', 'nationality' => 'Tuvaluan', 'continent' => 'Oceania'],
            ['name' => 'Uganda', 'code' => 'UG', 'nationality' => 'Ugandan', 'continent' => 'Africa'],
            ['name' => 'Ukraine', 'code' => 'UA', 'nationality' => 'Ukrainian', 'continent' => 'Europe'],
            ['name' => 'United Arab Emirates', 'code' => 'AE', 'nationality' => 'Emirati', 'continent' => 'Asia'],
            ['name' => 'United Kingdom', 'code' => 'GB', 'nationality' => 'British', 'continent' => 'Europe'],
            ['name' => 'United States', 'code' => 'US', 'nationality' => 'American', 'continent' => 'North America'],
            ['name' => 'United States Minor Outlying Islands', 'code' => 'UM', 'nationality' => 'American', 'continent' => 'North America'],
            ['name' => 'Uruguay', 'code' => 'UY', 'nationality' => 'Uruguayan', 'continent' => 'South America'],
            ['name' => 'Uzbekistan', 'code' => 'UZ', 'nationality' => 'Uzbek', 'continent' => 'Asia'],
            ['name' => 'Vanuatu', 'code' => 'VU', 'nationality' => 'Ni-Vanuatu', 'continent' => 'Oceania'],
            ['name' => 'Venezuela, Bolivarian Republic of', 'code' => 'VE', 'nationality' => 'Venezuelan', 'continent' => 'South America'],
            ['name' => 'Viet Nam', 'code' => 'VN', 'nationality' => 'Vietnamese', 'continent' => 'Asia'],
            ['name' => 'Virgin Islands, British', 'code' => 'VG', 'nationality' => 'British Virgin Islander', 'continent' => 'North America'],
            ['name' => 'Virgin Islands, U.S.', 'code' => 'VI', 'nationality' => 'Virgin Islander', 'continent' => 'North America'],
            ['name' => 'Wallis and Futuna', 'code' => 'WF', 'nationality' => 'Wallisian', 'continent' => 'Oceania'],
            ['name' => 'Western Sahara', 'code' => 'EH', 'nationality' => 'Sahrawi', 'continent' => 'Africa'],
            ['name' => 'Yemen', 'code' => 'YE', 'nationality' => 'Yemeni', 'continent' => 'Asia'],
            ['name' => 'Zambia', 'code' => 'ZM', 'nationality' => 'Zambian', 'continent' => 'Africa'],
            ['name' => 'Zimbabwe', 'code' => 'ZW', 'nationality' => 'Zimbabwean', 'continent' => 'Africa'],
        ];

        foreach ($countries as $key => $value) {
            Country::create($value);
        }
    }
}


