<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Country;

class CountrySeeder extends Seeder
{
    public function run()

    {
        Country::truncate();
        $countries = [
            ['name' => 'Afghanistan', 'code' => 'AF', 'nationality' => 'Afghan'],
            ['name' => 'Åland Islands', 'code' => 'AX', 'nationality' => 'Ålandic'],
            ['name' => 'Albania', 'code' => 'AL', 'nationality' => 'Albanian'],
            ['name' => 'Algeria', 'code' => 'DZ', 'nationality' => 'Algerian'],
            ['name' => 'American Samoa', 'code' => 'AS', 'nationality' => 'American Samoan'],
            ['name' => 'Andorra', 'code' => 'AD', 'nationality' => 'Andorran'],
            ['name' => 'Angola', 'code' => 'AO', 'nationality' => 'Angolan'],
            ['name' => 'Anguilla', 'code' => 'AI', 'nationality' => 'Anguillian'],
            ['name' => 'Antarctica', 'code' => 'AQ', 'nationality' => 'Antarctican'],
            ['name' => 'Antigua and Barbuda', 'code' => 'AG', 'nationality' => 'Antiguan'],
            ['name' => 'Argentina', 'code' => 'AR', 'nationality' => 'Argentine'],
            ['name' => 'Armenia', 'code' => 'AM', 'nationality' => 'Armenian'],
            ['name' => 'Aruba', 'code' => 'AW', 'nationality' => 'Aruban'],
            ['name' => 'Australia', 'code' => 'AU', 'nationality' => 'Australian'],
            ['name' => 'Austria', 'code' => 'AT', 'nationality' => 'Austrian'],
            ['name' => 'Azerbaijan', 'code' => 'AZ', 'nationality' => 'Azerbaijani'],
            ['name' => 'Bahamas', 'code' => 'BS', 'nationality' => 'Bahamian'],
            ['name' => 'Bahrain', 'code' => 'BH', 'nationality' => 'Bahraini'],
            ['name' => 'Bangladesh', 'code' => 'BD', 'nationality' => 'Bangladeshi'],
            ['name' => 'Barbados', 'code' => 'BB', 'nationality' => 'Barbadian'],
            ['name' => 'Belarus', 'code' => 'BY', 'nationality' => 'Belarusian'],
            ['name' => 'Belgium', 'code' => 'BE', 'nationality' => 'Belgian'],
            ['name' => 'Belize', 'code' => 'BZ', 'nationality' => 'Belizean'],
            ['name' => 'Benin', 'code' => 'BJ', 'nationality' => 'Beninese'],
            ['name' => 'Bermuda', 'code' => 'BM', 'nationality' => 'Bermudian'],
            ['name' => 'Bhutan', 'code' => 'BT', 'nationality' => 'Bhutanese'],
            ['name' => 'Bolivia, Plurinational State of', 'code' => 'BO', 'nationality' => 'Bolivian'],
            ['name' => 'Bonaire, Sint Eustatius and Saba', 'code' => 'BQ', 'nationality' => 'Bonairean'],
            ['name' => 'Bosnia and Herzegovina', 'code' => 'BA', 'nationality' => 'Bosnian'],
            ['name' => 'Botswana', 'code' => 'BW', 'nationality' => 'Botswana'],
            ['name' => 'Bouvet Island', 'code' => 'BV', 'nationality' => 'Bouvet Islander'],
            ['name' => 'Brazil', 'code' => 'BR', 'nationality' => 'Brazilian'],
            ['name' => 'British Indian Ocean Territory', 'code' => 'IO'],
            ['name' => 'Brunei Darussalam', 'code' => 'BN', 'nationality' => 'Bruneian'],
            ['name' => 'Bulgaria', 'code' => 'BG', 'nationality' => 'Bulgarian'],
            ['name' => 'Burkina Faso', 'code' => 'BF', 'nationality' => 'Burkinabè'],
            ['name' => 'Burundi', 'code' => 'BI', 'nationality' => 'Burundian'],
            ['name' => 'Cambodia', 'code' => 'KH', 'nationality' => 'Cambodian'],
            ['name' => 'Cameroon', 'code' => 'CM', 'nationality' => 'Cameroonian'],
            ['name' => 'Canada', 'code' => 'CA', 'nationality' => 'Canadian'],
            ['name' => 'Cape Verde', 'code' => 'CV', 'nationality' => 'Cabo Verdean'],
            ['name' => 'Cayman Islands', 'code' => 'KY', 'nationality' => 'Caymanian'],
            ['name' => 'Central African Republic', 'code' => 'CF', 'nationality' => 'Central African'],
            ['name' => 'Chad', 'code' => 'TD', 'nationality' => 'Chadian'],
            ['name' => 'Chile', 'code' => 'CL', 'nationality' => 'Chilean'],
            ['name' => 'China', 'code' => 'CN', 'nationality' => 'Chinese'],
            ['name' => 'Christmas Island', 'code' => 'CX', 'nationality' => 'Christmas Islander'],
            ['name' => 'Cocos (Keeling) Islands', 'code' => 'CC', 'nationality' => 'Cocos Islander'],
            ['name' => 'Colombia', 'code' => 'CO', 'nationality' => 'Colombian'],
            ['name' => 'Comoros', 'code' => 'KM', 'nationality' => 'Comorian'],
            ['name' => 'Congo', 'code' => 'CG', 'nationality' => 'Congolese'],
            ['name' => 'Congo, the Democratic Republic of the', 'code' => 'CD', 'nationality' => 'Congolese'],
            ['name' => 'Cook Islands', 'code' => 'CK', 'nationality' => 'Cook Islander'],
            ['name' => 'Costa Rica', 'code' => 'CR', 'nationality' => 'Costa Rican'],
            ['name' => 'Côte d\'Ivoire', 'code' => 'CI', 'nationality' => 'Ivorian'],
            ['name' => 'Croatia', 'code' => 'HR', 'nationality' => 'Croatian'],
            ['name' => 'Cuba', 'code' => 'CU', 'nationality' => 'Cuban'],
            ['name' => 'Curaçao', 'code' => 'CW', 'nationality' => 'Curaçaoan'],
            ['name' => 'Cyprus', 'code' => 'CY', 'nationality' => 'Cypriot'],
            ['name' => 'Czech Republic', 'code' => 'CZ', 'nationality' => 'Czech'],
            ['name' => 'Denmark', 'code' => 'DK', 'nationality' => 'Danish'],
            ['name' => 'Djibouti', 'code' => 'DJ', 'nationality' => 'Djiboutian'],
            ['name' => 'Dominica', 'code' => 'DM', 'nationality' => 'Dominican'],
            ['name' => 'Dominican Republic', 'code' => 'DO', 'nationality' => 'Dominican'],
            ['name' => 'Ecuador', 'code' => 'EC', 'nationality' => 'Ecuadorian'],
            ['name' => 'Egypt', 'code' => 'EG', 'nationality' => 'Egyptian'],
            ['name' => 'El Salvador', 'code' => 'SV', 'nationality' => 'Salvadoran'],
            ['name' => 'Equatorial Guinea', 'code' => 'GQ', 'nationality' => 'Equatoguinean'],
            ['name' => 'Eritrea', 'code' => 'ER', 'nationality' => 'Eritrean'],
            ['name' => 'Estonia', 'code' => 'EE', 'nationality' => 'Estonian'],
            ['name' => 'Ethiopia', 'code' => 'ET', 'nationality' => 'Ethiopian'],
            ['name' => 'Falkland Islands (Malvinas)', 'code' => 'FK', 'nationality' => 'Falkland Islander'],
            ['name' => 'Faroe Islands', 'code' => 'FO', 'nationality' => 'Faroese'],
            ['name' => 'Fiji', 'code' => 'FJ', 'nationality' => 'Fijian'],
            ['name' => 'Finland', 'code' => 'FI', 'nationality' => 'Finnish'],
            ['name' => 'France', 'code' => 'FR', 'nationality' => 'French'],
            ['name' => 'French Guiana', 'code' => 'GF', 'nationality' => 'French Guianese'],
            ['name' => 'French Polynesia', 'code' => 'PF', 'nationality' => 'French Polynesian'],
            ['name' => 'French Southern Territories', 'code' => 'TF', 'nationality' => 'French Southern Territories'],
            ['name' => 'Gabon', 'code' => 'GA', 'nationality' => 'Gabonese'],
            ['name' => 'Gambia', 'code' => 'GM', 'nationality' => 'Gambian'],
            ['name' => 'Georgia', 'code' => 'GE', 'nationality' => 'Georgian'],
            ['name' => 'Germany', 'code' => 'DE', 'nationality' => 'German'],
            ['name' => 'Ghana', 'code' => 'GH', 'nationality' => 'Ghanaian'],
            ['name' => 'Gibraltar', 'code' => 'GI', 'nationality' => 'Gibraltarian'],
            ['name' => 'Greece', 'code' => 'GR', 'nationality' => 'Greek'],
            ['name' => 'Greenland', 'code' => 'GL', 'nationality' => 'Greenlandic'],
            ['name' => 'Grenada', 'code' => 'GD', 'nationality' => 'Grenadian'],
            ['name' => 'Guadeloupe', 'code' => 'GP', 'nationality' => 'Guadeloupean'],
            ['name' => 'Guam', 'code' => 'GU', 'nationality' => 'Guamanian'],
            ['name' => 'Guatemala', 'code' => 'GT', 'nationality' => 'Guatemalan'],
            ['name' => 'Guernsey', 'code' => 'GG', 'nationality' => 'Guernsey'],
            ['name' => 'Guinea', 'code' => 'GN', 'nationality' => 'Guinean'],
            ['name' => 'Guinea-Bissau', 'code' => 'GW', 'nationality' => 'Bissau-Guinean'],
            ['name' => 'Guyana', 'code' => 'GY', 'nationality' => 'Guyanese'],
            ['name' => 'Haiti', 'code' => 'HT', 'nationality' => 'Haitian'],
            ['name' => 'Heard Island and McDonald Mcdonald Islands', 'code' => 'HM', 'nationality' => 'Heard Island or McDonald Islander'],
            ['name' => 'Holy See (Vatican City State)', 'code' => 'VA', 'nationality' => 'Vatican'],
            ['name' => 'Honduras', 'code' => 'HN', 'nationality' => 'Honduran'],
            ['name' => 'Hong Kong', 'code' => 'HK', 'nationality' => 'Hong Konger'],
            ['name' => 'Hungary', 'code' => 'HU', 'nationality' => 'Hungarian'],
            ['name' => 'Iceland', 'code' => 'IS', 'nationality' => 'Icelandic'],
            ['name' => 'India', 'code' => 'IN', 'nationality' => 'Indian'],
            ['name' => 'Indonesia', 'code' => 'ID', 'nationality' => 'Indonesian'],
            ['name' => 'Iran, Islamic Republic of', 'code' => 'IR', 'nationality' => 'Iranian'],
            ['name' => 'Iraq', 'code' => 'IQ', 'nationality' => 'Iraqi'],
            ['name' => 'Ireland', 'code' => 'IE', 'nationality' => 'Irish'],
            ['name' => 'Isle of Man', 'code' => 'IM', 'nationality' => 'Manx'],
            ['name' => 'Israel', 'code' => 'IL', 'nationality' => 'Israeli'],
            ['name' => 'Italy', 'code' => 'IT', 'nationality' => 'Italian'],
            ['name' => 'Jamaica', 'code' => 'JM', 'nationality' => 'Jamaican'],
            ['name' => 'Japan', 'code' => 'JP', 'nationality' => 'Japanese'],
            ['name' => 'Jersey', 'code' => 'JE', 'nationality' => 'Jerseyman'],
            ['name' => 'Jordan', 'code' => 'JO', 'nationality' => 'Jordanian'],
            ['name' => 'Kazakhstan', 'code' => 'KZ', 'nationality' => 'Kazakhstani'],
            ['name' => 'Kenya', 'code' => 'KE', 'nationality' => 'Kenyan'],
            ['name' => 'Kiribati', 'code' => 'KI', 'nationality' => 'I-Kiribati'],
            ['name' => 'Korea, Democratic People\'s Republic of', 'code' => 'KP', 'nationality' => 'North Korean'],
            ['name' => 'Korea, Republic of', 'code' => 'KR', 'nationality' => 'South Korean'],
            ['name' => 'Kuwait', 'code' => 'KW', 'nationality' => 'Kuwaiti'],
            ['name' => 'Kyrgyzstan', 'code' => 'KG', 'nationality' => 'Kyrgyzstani'],
            ['name' => 'Lao People\'s Democratic Republic', 'code' => 'LA', 'nationality' => 'Lao'],
            ['name' => 'Latvia', 'code' => 'LV', 'nationality' => 'Latvian'],
            ['name' => 'Lebanon', 'code' => 'LB', 'nationality' => 'Lebanese'],
            ['name' => 'Lesotho', 'code' => 'LS', 'nationality' => 'Basotho'],
            ['name' => 'Liberia', 'code' => 'LR', 'nationality' => 'Liberian'],
            ['name' => 'Libya', 'code' => 'LY', 'nationality' => 'Libyan'],
            ['name' => 'Liechtenstein', 'code' => 'LI', 'nationality' => 'Liechtensteiner'],
            ['name' => 'Lithuania', 'code' => 'LT', 'nationality' => 'Lithuanian'],
            ['name' => 'Luxembourg', 'code' => 'LU', 'nationality' => 'Luxembourgish'],
            ['name' => 'Macao', 'code' => 'MO', 'nationality' => 'Macanese'],
            ['name' => 'Macedonia, the Former Yugoslav Republic of', 'code' => 'MK', 'nationality' => 'Macedonian'],
            ['name' => 'Madagascar', 'code' => 'MG', 'nationality' => 'Malagasy'],
            ['name' => 'Malawi', 'code' => 'MW', 'nationality' => 'Malawian'],
            ['name' => 'Malaysia', 'code' => 'MY', 'nationality' => 'Malaysian'],
            ['name' => 'Maldives', 'code' => 'MV', 'nationality' => 'Maldivian'],
            ['name' => 'Mali', 'code' => 'ML', 'nationality' => 'Malian'],
            ['name' => 'Malta', 'code' => 'MT', 'nationality' => 'Maltese'],
            ['name' => 'Marshall Islands', 'code' => 'MH', 'nationality' => 'Marshallese'],
            ['name' => 'Martinique', 'code' => 'MQ', 'nationality' => 'Martiniquais'],
            ['name' => 'Mauritania', 'code' => 'MR', 'nationality' => 'Mauritanian'],
            ['name' => 'Mauritius', 'code' => 'MU', 'nationality' => 'Mauritian'],
            ['name' => 'Mayotte', 'code' => 'YT', 'nationality' => 'Mahorais'],
            ['name' => 'Mexico', 'code' => 'MX', 'nationality' => 'Mexican'],
            ['name' => 'Micronesia, Federated States of', 'code' => 'FM', 'nationality' => 'Micronesian'],
            ['name' => 'Moldova, Republic of', 'code' => 'MD', 'nationality' => 'Moldovan'],
            ['name' => 'Monaco', 'code' => 'MC', 'nationality' => 'Monegasque'],
            ['name' => 'Mongolia', 'code' => 'MN', 'nationality' => 'Mongolian'],
            ['name' => 'Montenegro', 'code' => 'ME', 'nationality' => 'Montenegrin'],
            ['name' => 'Montserrat', 'code' => 'MS', 'nationality' => 'Montserratian'],
            ['name' => 'Morocco', 'code' => 'MA', 'nationality' => 'Moroccan'],
            ['name' => 'Mozambique', 'code' => 'MZ', 'nationality' => 'Mozambican'],
            ['name' => 'Myanmar', 'code' => 'MM', 'nationality' => 'Myanmarese'],
            ['name' => 'Namibia', 'code' => 'NA', 'nationality' => 'Namibian'],
            ['name' => 'Nauru', 'code' => 'NR', 'nationality' => 'Nauruan'],
            ['name' => 'Nepal', 'code' => 'NP', 'nationality' => 'Nepali'],
            ['name' => 'Netherlands', 'code' => 'NL', 'nationality' => 'Dutch'],
            ['name' => 'New Caledonia', 'code' => 'NC', 'nationality' => 'New Caledonian'],
            ['name' => 'New Zealand', 'code' => 'NZ', 'nationality' => 'New Zealander'],
            ['name' => 'Nicaragua', 'code' => 'NI', 'nationality' => 'Nicaraguan'],
            ['name' => 'Niger', 'code' => 'NE', 'nationality' => 'Nigerien'],
            ['name' => 'Nigeria', 'code' => 'NG', 'nationality' => 'Nigerian'],
            ['name' => 'Niue', 'code' => 'NU', 'nationality' => 'Niuean'],
            ['name' => 'Norfolk Island', 'code' => 'NF', 'nationality' => 'Norfolk Islander'],
            ['name' => 'Northern Mariana Islands', 'code' => 'MP', 'nationality' => 'Northern Mariana Islander'],
            ['name' => 'Norway', 'code' => 'NO', 'nationality' => 'Norwegian'],
            ['name' => 'Oman', 'code' => 'OM', 'nationality' => 'Omani'],
            ['name' => 'Pakistan', 'code' => 'PK', 'nationality' => 'Pakistani'],
            ['name' => 'Palau', 'code' => 'PW', 'nationality' => 'Palauan'],
            ['name' => 'Palestine, State of', 'code' => 'PS', 'nationality' => 'Palestinian'],
            ['name' => 'Panama', 'code' => 'PA', 'nationality' => 'Panamanian'],
            ['name' => 'Papua New Guinea', 'code' => 'PG', 'nationality' => 'Papua New Guinean'],
            ['name' => 'Paraguay', 'code' => 'PY', 'nationality' => 'Paraguayan'],
            ['name' => 'Peru', 'code' => 'PE', 'nationality' => 'Peruvian'],
            ['name' => 'Philippines', 'code' => 'PH', 'nationality' => 'Filipino'],
            ['name' => 'Pitcairn', 'code' => 'PN', 'nationality' => 'Pitcairn Islander'],
            ['name' => 'Poland', 'code' => 'PL', 'nationality' => 'Polish'],
            ['name' => 'Portugal', 'code' => 'PT', 'nationality' => 'Portuguese'],
            ['name' => 'Puerto Rico', 'code' => 'PR', 'nationality' => 'Puerto Rican'],
            ['name' => 'Qatar', 'code' => 'QA', 'nationality' => 'Qatari'],
            ['name' => 'Réunion', 'code' => 'RE', 'nationality' => 'Réunionese'],
            ['name' => 'Romania', 'code' => 'RO', 'nationality' => 'Romanian'],
            ['name' => 'Russian Federation', 'code' => 'RU', 'nationality' => 'Russian'],
            ['name' => 'Rwanda', 'code' => 'RW', 'nationality' => 'Rwandan'],
            ['name' => 'Saint Barthélemy', 'code' => 'BL', 'nationality' => 'Saint Barthélemy'],
            ['name' => 'Saint Helena, Ascension and Tristan da Cunha', 'code' => 'SH', 'nationality' => 'Saint Helenian'],
            ['name' => 'Saint Kitts and Nevis', 'code' => 'KN', 'nationality' => 'Kittitian'],
            ['name' => 'Saint Lucia', 'code' => 'LC', 'nationality' => 'Saint Lucian'],
            ['name' => 'Saint Martin (French part)', 'code' => 'MF', 'nationality' => 'Saint Martinois'],
            ['name' => 'Saint Pierre and Miquelon', 'code' => 'PM', 'nationality' => 'Saint-Pierrais'],
            ['name' => 'Saint Vincent and the Grenadines', 'code' => 'VC', 'nationality' => 'Saint Vincentian'],
            ['name' => 'Samoa', 'code' => 'WS', 'nationality' => 'Samoan'],
            ['name' => 'San Marino', 'code' => 'SM', 'nationality' => 'Sammarinese'],
            ['name' => 'Sao Tome and Principe', 'code' => 'ST', 'nationality' => 'Sao Tomean'],
            ['name' => 'Saudi Arabia', 'code' => 'SA', 'nationality' => 'Saudi'],
            ['name' => 'Senegal', 'code' => 'SN', 'nationality' => 'Senegalese'],
            ['name' => 'Serbia', 'code' => 'RS', 'nationality' => 'Serbian'],
            ['name' => 'Seychelles', 'code' => 'SC', 'nationality' => 'Seychellois'],
            ['name' => 'Sierra Leone', 'code' => 'SL', 'nationality' => 'Sierra Leonean'],
            ['name' => 'Singapore', 'code' => 'SG', 'nationality' => 'Singaporean'],
            ['name' => 'Sint Maarten (Dutch part)', 'code' => 'SX', 'nationality' => 'Sint Maartener'],
            ['name' => 'Slovakia', 'code' => 'SK', 'nationality' => 'Slovak'],
            ['name' => 'Slovenia', 'code' => 'SI', 'nationality' => 'Slovenian'],
            ['name' => 'Solomon Islands', 'code' => 'SB', 'nationality' => 'Solomon Islander'],
            ['name' => 'Somalia', 'code' => 'SO', 'nationality' => 'Somali'],
            ['name' => 'South Africa', 'code' => 'ZA', 'nationality' => 'South African'],
            ['name' => 'South Georgia and the South Sandwich Islands', 'code' => 'GS'],
            ['name' => 'South Sudan', 'code' => 'SS', 'nationality' => 'South Sudanese'],
            ['name' => 'Spain', 'code' => 'ES', 'nationality' => 'Spanish'],
            ['name' => 'Sri Lanka', 'code' => 'LK', 'nationality' => 'Sri Lankan'],
            ['name' => 'Sudan', 'code' => 'SD', 'nationality' => 'Sudanese'],
            ['name' => 'Suriname', 'code' => 'SR', 'nationality' => 'Surinamese'],
            ['name' => 'Svalbard and Jan Mayen', 'code' => 'SJ', 'nationality' => 'Svalbardian'],
            ['name' => 'Swaziland', 'code' => 'SZ', 'nationality' => 'Swazi'],
            ['name' => 'Sweden', 'code' => 'SE', 'nationality' => 'Swedish'],
            ['name' => 'Switzerland', 'code' => 'CH', 'nationality' => 'Swiss'],
            ['name' => 'Syrian Arab Republic', 'code' => 'SY', 'nationality' => 'Syrian'],
            ['name' => 'Taiwan', 'code' => 'TW', 'nationality' => 'Taiwanese'],
            ['name' => 'Tajikistan', 'code' => 'TJ', 'nationality' => 'Tajikistani'],
            ['name' => 'Tanzania, United Republic of', 'code' => 'TZ', 'nationality' => 'Tanzanian'],
            ['name' => 'Thailand', 'code' => 'TH', 'nationality' => 'Thai'],
            ['name' => 'Timor-Leste', 'code' => 'TL', 'nationality' => 'Timorese'],
            ['name' => 'Togo', 'code' => 'TG', 'nationality' => 'Togolese'],
            ['name' => 'Tokelau', 'code' => 'TK', 'nationality' => 'Tokelauan'],
            ['name' => 'Tonga', 'code' => 'TO', 'nationality' => 'Tongan'],
            ['name' => 'Trinidad and Tobago', 'code' => 'TT', 'nationality' => 'Trinidadian'],
            ['name' => 'Tunisia', 'code' => 'TN', 'nationality' => 'Tunisian'],
            ['name' => 'Turkey', 'code' => 'TR', 'nationality' => 'Turkish'],
            ['name' => 'Turkmenistan', 'code' => 'TM', 'nationality' => 'Turkmen'],
            ['name' => 'Turks and Caicos Islands', 'code' => 'TC', 'nationality' => 'Turks and Caicos Islander'],
            ['name' => 'Tuvalu', 'code' => 'TV', 'nationality' => 'Tuvaluan'],
            ['name' => 'Uganda', 'code' => 'UG', 'nationality' => 'Ugandan'],
            ['name' => 'Ukraine', 'code' => 'UA', 'nationality' => 'Ukrainian'],
            ['name' => 'United Arab Emirates', 'code' => 'AE', 'nationality' => 'Emirati'],
            ['name' => 'United Kingdom', 'code' => 'GB', 'nationality' => 'British'],
            ['name' => 'United States', 'code' => 'US', 'nationality' => 'American'],
            ['name' => 'United States Minor Outlying Islands', 'code' => 'UM', 'nationality' => 'American'],
            ['name' => 'Uruguay', 'code' => 'UY', 'nationality' => 'Uruguayan'],
            ['name' => 'Uzbekistan', 'code' => 'UZ', 'nationality' => 'Uzbek'],
            ['name' => 'Vanuatu', 'code' => 'VU', 'nationality' => 'Ni-Vanuatu'],
            ['name' => 'Venezuela, Bolivarian Republic of', 'code' => 'VE', 'nationality' => 'Venezuelan'],
            ['name' => 'Viet Nam', 'code' => 'VN', 'nationality' => 'Vietnamese'],
            ['name' => 'Virgin Islands, British', 'code' => 'VG', 'nationality' => 'British Virgin Islander'],
            ['name' => 'Virgin Islands, U.S.', 'code' => 'VI', 'nationality' => 'Virgin Islander'],
            ['name' => 'Wallis and Futuna', 'code' => 'WF', 'nationality' => 'Wallisian'],
            ['name' => 'Western Sahara', 'code' => 'EH', 'nationality' => 'Sahrawi'],
            ['name' => 'Yemen', 'code' => 'YE', 'nationality' => 'Yemeni'],
            ['name' => 'Zambia', 'code' => 'ZM', 'nationality' => 'Zambian'],
            ['name' => 'Zimbabwe', 'code' => 'ZW', 'nationality' => 'Zimbabwean'],
        ];

        foreach ($countries as $key => $value) {
            Country::create($value);
        }
    }
}


